ALTER TABLE testimonials
  ADD COLUMN IF NOT EXISTS author_image   VARCHAR(500)  NULL,
  ADD COLUMN IF NOT EXISTS company        VARCHAR(255)  NULL,
  ADD COLUMN IF NOT EXISTS designation    VARCHAR(255)  NULL,
  ADD COLUMN IF NOT EXISTS product_bought VARCHAR(255)  NULL;
