CREATE TABLE IF NOT EXISTS not_found_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  url VARCHAR(500) NOT NULL,
  referrer VARCHAR(500) NULL,
  user_agent VARCHAR(255) NULL,
  hits INT NOT NULL DEFAULT 1,
  last_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_url (url)
);
